export enum PrintMaterialUseType {
    CUSTOM_PRINTS = "CUSTOM_PRINTS",
    STORE_PRINTS = "STORE_PRINTS",
    STORE_PRINTS_AND_CUSTOM_PRINTS = "STORE_PRINTS_AND_CUSTOM_PRINTS",
    INTERNAL_USE = "INTERNAL_USE"
}
